import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import getCurrentUser from "./actions/getCurrentUser";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FitneHeal",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
          attribute="class"
          forcedTheme="light"
          storageKey="fineHeal-theme"
          >
      
            {children}
            <div className="flex flex-col justify-center items-center">
              <h1>FitneHealBot</h1>
            </div>
          </ThemeProvider>
        </body>
      
    </html>
  );
}
