import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FitneHeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={inter.className}>
          <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="fineHeal-theme"
          >
            {children}
            <div>
              <h1>FitneHealBot</h1>
            </div>
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
